[theme]
primaryColor = "#305496"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F4F9"
textColor = "#1A1A1A"
font = "sans serif"

[server]
maxUploadSize = 50
enableCORS = false
enableXsrfProtection = true

[browser]
gatherUsageStats = false
